server:
  port: 9999

spring:
  application:
    name: maintenance
  profiles:
    active: dev
  # 依赖循环解决
  main:
    allow-circular-references: true
  # swagger 冲突解决
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    # 单次上传文件大小限制
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 40
    # 活跃时间
    keep-alive-seconds: 200
    # 队列容量
    queue-capacity: 100

# mybatis-plus
mybatis-plus:
  type-aliases-package: com.device.entity
  mapper-locations: classpath*:com/device/**/*.xml
  configuration:
    # 输出日志到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 关闭日志输出
#    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl